# Generated by Django 3.2 on 2021-04-08 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='viza',
            field=models.CharField(choices=[('Y', 'Да'), ('N', 'Нет')], max_length=5, null=True),
        ),
    ]
