# Generated by Django 3.2 on 2021-04-08 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travapp', '0002_country_viza'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='viza',
        ),
        migrations.AddField(
            model_name='country',
            name='description',
            field=models.TextField(null=True, verbose_name='Туристическое описание'),
        ),
        migrations.AddField(
            model_name='country',
            name='mountain',
            field=models.CharField(choices=[('Y', 'Да'), ('N', 'Нет')], max_length=5, null=True, verbose_name='Наличие гор'),
        ),
        migrations.AddField(
            model_name='country',
            name='sea',
            field=models.CharField(choices=[('Y', 'Да'), ('N', 'Нет')], max_length=5, null=True, verbose_name='Наличие моря'),
        ),
        migrations.AddField(
            model_name='country',
            name='visa',
            field=models.CharField(choices=[('Y', 'Да'), ('N', 'Нет')], max_length=5, null=True, verbose_name='Нужна ли виза беларусам'),
        ),
        migrations.AlterField(
            model_name='continent',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Название'),
        ),
    ]
