# Generated by Django 3.2 on 2021-04-08 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travapp', '0003_auto_20210408_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='mountain',
            field=models.CharField(choices=[('Y', 'Да'), ('N', 'Нет')], max_length=5, null=True, verbose_name='Наличие горнолыжных курортов'),
        ),
        migrations.AlterField(
            model_name='country',
            name='sea',
            field=models.CharField(choices=[('Y', 'Да'), ('N', 'Нет')], max_length=5, null=True, verbose_name='Наличие морских курортов'),
        ),
    ]
