# Generated by Django 3.2 on 2021-04-08 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travapp', '0004_auto_20210408_1836'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(null=True, verbose_name='Комментарий')),
                ('rating', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=5, null=True, verbose_name='Оценка')),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='travapp.country')),
            ],
            options={
                'verbose_name': 'Континент',
                'verbose_name_plural': 'Континенты',
            },
        ),
    ]
