# Generated by Django 3.2 on 2021-04-08 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travapp', '0005_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': 'Комментарий', 'verbose_name_plural': 'Комментарии'},
        ),
    ]
