# Generated by Django 3.2 on 2021-04-14 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travapp', '0006_alter_comment_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='mountain',
            field=models.CharField(choices=[('Да', 'Да'), ('Нет', 'Нет')], max_length=5, null=True, verbose_name='Наличие горнолыжных курортов'),
        ),
        migrations.AlterField(
            model_name='country',
            name='sea',
            field=models.CharField(choices=[('Да', 'Да'), ('Нет', 'Нет')], max_length=5, null=True, verbose_name='Наличие морских курортов'),
        ),
        migrations.AlterField(
            model_name='country',
            name='visa',
            field=models.CharField(choices=[('Да', 'Да'), ('Нет', 'Нет')], max_length=5, null=True, verbose_name='Нужна ли виза беларусам'),
        ),
    ]
