# Generated by Django 3.2 on 2021-04-14 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travapp', '0007_auto_20210414_1700'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='name',
            field=models.CharField(max_length=100, null=True, verbose_name='Короткий комментарий'),
        ),
    ]
