# Generated by Django 3.2 on 2021-04-14 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travapp', '0008_comment_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='name',
        ),
    ]
