# Generated by Django 3.2 on 2021-04-16 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travapp', '0011_auto_20210416_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='rating',
            field=models.IntegerField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], null=True, verbose_name='Оценка'),
        ),
    ]
