# Generated by Django 3.2 on 2021-04-16 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travapp', '0013_alter_comment_rating'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['name'], 'verbose_name': 'Комментарий', 'verbose_name_plural': 'Комментарии'},
        ),
        migrations.AlterModelOptions(
            name='continent',
            options={'ordering': ['name'], 'verbose_name': 'Континент', 'verbose_name_plural': 'Континенты'},
        ),
        migrations.AlterModelOptions(
            name='country',
            options={'ordering': ['name'], 'verbose_name': 'Страна', 'verbose_name_plural': 'Страны'},
        ),
    ]
